Fixed issue #649 Broken Link
openaustralia/righttoknow pull request #681
Opened 2017-03-24 13:31 UTC by Anishka0107

This pull request tries to fix the issue https://github.com/openaustralia/righttoknow/issues/649
The link Statement of IP Principles for Australian Government Agencies on the page https://www.righttoknow.org.au/help/requesting#reuse is broken. It initially pointed to a page which does not exist i.e., https://www.ag.gov.au/RightsAndProtections/IntellectualProperty/Documents/StatementofIPprinciplesforAusGovagencies.pdf
Now it links to the page http://www.ags.gov.au/publications/express-law/el125.pdf

2017-03-28 01:44 UTC, equivalentideas commented
Thanks @Anishka0107 

I'm a little surprised there's nothing more up to date that 2010 for their latest statement, so I did a little searching and found this https://www.communications.gov.au/policy/policy-listing/australian-government-intellectual-property-rules. Is the PDF linked to their relevant?

We'll also need to update the quote below the link with something from the new principles that makes the same point.

2017-03-28 01:56 UTC, equivalentideas requested changes
* [ ] Check if this document is the more up-to-date statement https://www.communications.gov.au/policy/policy-listing/australian-government-intellectual-property-rules
* [ ] Update the quote below to something that makes the same point from the new document.

2017-03-28 01:56 UTC, equivalentideas commented
I've just added those steps as a review on GitHub :)

2017-03-28 03:29 UTC, Anishka0107 commented
@equivalentideas 
Sir, Could you please see the pdf https://www.communications.gov.au/file/2015/download?token=nmvWmdrj they have provided on the site you mentioned. I have attached a relevant section of it as an image(below)
![textonpdf](https://cloud.githubusercontent.com/assets/16884926/24387617/bfac2692-1393-11e7-82dd-fdea5fb791a4.jpg)
This states that the latest amendment made was in 2010. Moreover, the link which you added is the latest, but I guess it does not include much detail about the Statement of IP Principles.
Could you please tell me which link is more appropriate?
I will make the change as you suggest.

2017-05-16 06:36 UTC, equivalentideas commented
I think @benrfairless might be the best person to review this. I'm going to assign you Ben, but feel free to throw it back at me :D 

Thanks @Anishka0107 !

2017-05-16 12:00 UTC, benrfairless requested changes
I still think that the correct file is https://www.communications.gov.au/file/20151/download?token=nmvWmdrj, which I got from https://www.communications.gov.au/policy/policy-listing/australian-government-intellectual-property-rules. This are the actual rules in effect - not recommendations made.

2021-02-23 05:20 UTC, mlandauer commented
Looking at the most recent comment from @ben it looks like the now the most recent relevant document is most likely the "Intellectual property principles for Commonwealth entities" updated Feb 2019 available at https://www.communications.gov.au/documents/intellectual-property-principles-commonwealth-entities.

It says in section 11(b):
"Consistent with the need for free and open re-use and adaptation, public sector information should be licensed by entities under the Creative Commons BY standard as the default."

2021-02-23 05:25 UTC, mlandauer commented
I've applied the fix in https://github.com/openaustralia/righttoknow/commit/d4064088cdf464ec7f6bddfcf459059c42a80e4e. Closing this PR in favour of that change

2021-02-23 05:25 UTC, closed without merging