Resolved #669 on 0.26-upgrade
openaustralia/righttoknow pull request #685
Opened 2017-04-02 14:28 UTC by Keerti-Gautam

As a genuine concern pointed out by @benrfairless in #684 , I am creating a new PR into the branch `0.26-upgrade` so the changes can be merged in a single hit. 
This change of the `max-width: 11em` which puts back "Make a Request" in a single line, works well with older as well as newer versions of Right To Know.

2017-04-03 05:35 UTC, equivalentideas requested changes
Thanks for this contribution @Keerti-Gautam :) Fixing things like this will make the upgrade much quicker 💯 

I've left a comment requesting changes of the style of your css to match the rest of the file. It's important files are consistent, and when making a PR to an open source project make sure you're change is in line with the projects code style.

Also in the future it would be great to have a more descriptive commit message and Pull request. Here's a couple of great guides I often refer to myself :) :

https://github.com/blog/1943-how-to-write-the-perfect-pull-request

https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

2017-04-03 05:35 UTC, equivalentideas commented on assets/stylesheets/responsive/custom.scss
> +    max-width: 11em;
This looks like it uses different indentation and an extra line of whitespace compared to the rest of this file. Could you please fix add a commit to correct that @Keerti-Gautam

2017-04-03 06:12 UTC, Keerti-Gautam commented
Hi Luke,
I had added a thorough description of the changes on the last PR I made #684, which required a version check as correctly pointed out by @benrfairless so I created another PR here. If it was missed out, I will just add the content here for you to review! 
Thanks a lot! :smile: 
...
Upon upgrading the version of alaveteli, this button was somehow broken and 'Make a Request' was coming on two lines. It was because of the addition of a class in alaveteli which is `body_listing__request-button`, which made me realize that this was a design altercation in alaveteli and not in RightToKnow.
But I searched a little more and came to find out that [WhatDoTheyKnow](https://www.whatdotheyknow.com/) is another FOI website used in UK and it uses the current alaveteli version but still, 'Make a Request' comes in a single line.
Hence it was clear that some changes had to be made in RightToKnow to fix the issue.

*Changes Made:*
The `max-width` of the button was hence changed from its inherited 10em to 11em.
Screenshot attached.

![screenshot](https://cloud.githubusercontent.com/assets/19797779/24597282/663058ee-1862-11e7-823c-d45fdb675eac.png)

2017-04-05 21:20 UTC, equivalentideas approved these changes

2017-04-05 21:20 UTC, equivalentideas commented
Very nice @Keerti-Gautam :) This does the job!

2017-04-05 21:20 UTC, merged